language: python
python:
    - "3.5"
    - "3.6"
cache: pip
install:
    - pip install -r requirements.txt
before_script:
    # Something
script:
    # - python tests.py
    - py.test source/tests/tests.py --pep8 source/tests/ -v --cov source/tests/ --cov-report term-missing

after_success:
    - coveralls
